clear all
close all 

%% Current analysis: Standard Specification
% Need to change:
% 1) the cd() file path,
% 2) the data names for the data and coefficients (latter multiple locations)
% 3) the export data file names.
% 4) change math as needed. 

%% Introduction. 
% This script runs the conditional forecast from Bernanke and Blanchard (2023)
% We run our conditional forecast using three assumptions: that v/u 
% declines to 0.8 after 8 quarters, that v/u declines to 1.2 after 8 
% quarters, and that v/u remains about steady at 1.8 (it technically slightly 
% increases over 8 quarters). There are three arguments of interest that can be 
% changed in the function arguments below:
%
%   1) vu_decline_val, which is the value to which v/u will decline to,
%   after which it stays put.
%
%   2) vu_quarters_decline, which specifies over what period v/u declines
%   to the value specified in vu_decline_val
%
% Final results are stored in the "result{i}" variable and are outputted to
% the corresponding Excel sheet defined below.

% Please contact Sam Boocker (Brookings Institution) for further questions.


%% Import and format data
base_dir = pwd();
cd("..\Replication Package\Code and Data\(2) Regressions\Output Data (Full Sample)\")
data = readtable("eq_simulations_data.xls", VariableNamingRule = "preserve");

data_orig = data;
data = data(data.period >= datetime(2022,4,1), :); 

%% Calculate wage correction constant. 
magpty_star = 1;     % Long run magpty.
shortage_star = 10;  % Long run shortage.
vu_star = 1.2;       % Long run targeted vu. 

% Import estimated coefficients. 
format long
gw_beta = readtable("eq_coefficients", 'Sheet', "gw");
gcpi_beta = readtable("eq_coefficients", 'Sheet', "gcpi");
cf1_beta = readtable("eq_coefficients", 'Sheet', "cf1");
cf10_beta = readtable("eq_coefficients", 'Sheet', "cf10");

wage_constant = calculate_wage_constant(gw_beta, gcpi_beta, ...
    magpty_star, shortage_star, vu_star);

result1 = conditional_forecast(data, wage_constant, magpty_star, shortage_star, ...
    .8, ...  % Change the value of vu_decline_value.
    8, ...   % Change the value of vu_quarters_decline. 
    100);    % Change the long term horizon of the forecast (in years). 
    
result2 = conditional_forecast(data, wage_constant, magpty_star, shortage_star, ...
    1.2, 8, 100);

result3 = conditional_forecast(data, wage_constant, magpty_star, shortage_star, ...
    1.8, 8, 100);

clear gw_beta gcpi_beta cf1_beta cf10_beta magpty_star shortage_star vu_star

%% Export results. 
cd("..\Replication Package\Code and Data\(3) Core Results\Conditional Forecasts\Output Data")

writetable(result1, "terminal_low.xlsx")
writetable(result2, "terminal_mid.xlsx")
writetable(result3, "terminal_high.xlsx")

%% Function to calculate the wage consgant. 
function wage_constant = calculate_wage_constant(gw_beta, gcpi_beta, ...
    magpty, shortage, vu_star)
    wage_constant = (- sum(gw_beta.beta(10:13)) * vu_star) - ...
    (1 - sum(gw_beta.beta(1:4))) * (...
        (gcpi_beta.beta(1) / (1 - sum(gcpi_beta.beta(2:5))) + ...
            gw_beta.beta(9) / (1 - sum(gw_beta.beta(1:4)))) * magpty + ...
        sum(gcpi_beta.beta(21:25)) / (1 - sum(gcpi_beta.beta(2:5))) * shortage + ...
        gcpi_beta.beta(26) / (1 - sum(gcpi_beta.beta(2:5))));
end


%% Function that runs the conditional forecast. 
function out_data = conditional_forecast(data, wage_constant, magpty_star, shortage_star, ...
    vu_decline_val, vu_quarters_decline, years)

    % Import estimated coefficients. 
    format long
    gw_beta = readtable("eq_coefficients", 'Sheet', "gw");
    gcpi_beta = readtable("eq_coefficients", 'Sheet', "gcpi");
    cf1_beta = readtable("eq_coefficients", 'Sheet', "cf1");
    cf10_beta = readtable("eq_coefficients", 'Sheet', "cf10");

    % Define period. 
    period = data.period.';
    forecast_num_years = years;

    timesteps = size(data,1) + 4*forecast_num_years;

    % Initialize data

    % Endogenous variables
    gw = data.gw.';
    gcpi = data.gcpi.';
    cf1 = data.cf1.';
    cf10 = data.cf10.';
    diffcpicf = data.diffcpicf.';

    % Exogenous shocks
    grpe = data.grpe.';
    grpf = data.grpf.';
    vu = data.vu.';
    shortage = data.shortage.';
    magpty = data.magpty.';

    % Initialize endogenous simulation variables. 
    gw_simul = gw(1:4);
    gcpi_simul = gcpi(1:4);
    cf1_simul = cf1(1:4);
    cf10_simul = cf10(1:4);
    diffcpicf_simul = diffcpicf(1:4);

    % Initialize exogenous shock variables for simulation.
    grpe_simul = grpe;
    grpf_simul = grpf;
    vu_simul = vu;
    shortage_simul = shortage;
    
    % Calculate slope of vu
    vu_slope = (vu_decline_val-vu(4))/vu_quarters_decline;

    % Define dummy variables. 
    dummy2020_q2 = 0.0;
    dummy2020_q3 = 0.0; 

    for t = 5:timesteps

        % Set exogenous variables to desired values
        grpe_simul(t) = 0;
        grpf_simul(t) = 0;
        shortage_simul(t) = shortage_star;

        if vu_slope >= 0
            vu_simul(t) = min(vu_decline_val, vu_simul(t-1) +...
            vu_slope);
        else
            vu_simul(t) = max(vu_decline_val, vu_simul(t-1) +...
            vu_slope);
        end

        % Update period 
        period(t) = period(t-1) + calmonths(3);

        % How labor productivity evolves
        magpty(t) = magpty_star;

        % Add in the dummy variables. Do we need this?
        % Shouldn't dummy variables be 0 by construction at steady state?
        if t == 7
            dummy2020_q2 = gw_beta.beta(18);
        else
            dummy2020_q2 = 0.0;
        end

        if t == 8
            dummy2020_q3 = gw_beta.beta(19);
        else
            dummy2020_q3 = 0.0;
        end
    
        % Forecast equations
        gw_simul(t) = gw_beta.beta(1)*gw_simul(t-1) +...
        gw_beta.beta(2)*gw_simul(t-2) + ...
        gw_beta.beta(3)*gw_simul(t-3) + ...
        gw_beta.beta(4)*gw_simul(t-4) + ...
        gw_beta.beta(5)*cf1_simul(t-1) + ...
        gw_beta.beta(6)*cf1_simul(t-2) + ...
        gw_beta.beta(7)*cf1_simul(t-3) + ...
        gw_beta.beta(8)*cf1_simul(t-4) + ...
        gw_beta.beta(9)*magpty(t-1) + ...
        gw_beta.beta(10)*vu_simul(t-1) + ...
        gw_beta.beta(11)*vu_simul(t-2) + ...
        gw_beta.beta(12)*vu_simul(t-3) + ...
        gw_beta.beta(13)*vu_simul(t-4) + ...
        gw_beta.beta(14)*diffcpicf_simul(t-1) + ...
        gw_beta.beta(15)*diffcpicf_simul(t-2) + ...
        gw_beta.beta(16)*diffcpicf_simul(t-3) + ...
        gw_beta.beta(17)*diffcpicf_simul(t-4) + ...
        wage_constant;
        
        gcpi_simul(t) =  gcpi_beta.beta(1)*magpty(t) +...
        gcpi_beta.beta(2)*gcpi_simul(t-1) +...
        gcpi_beta.beta(3)*gcpi_simul(t-2) +...
        gcpi_beta.beta(4)*gcpi_simul(t-3) +...
        gcpi_beta.beta(5)*gcpi_simul(t-4) + ...
        gcpi_beta.beta(6)*gw_simul(t) + ...
        gcpi_beta.beta(7)*gw_simul(t-1)+...
        gcpi_beta.beta(8)*gw_simul(t-2) +...
        gcpi_beta.beta(9)*gw_simul(t-3) + ...
        gcpi_beta.beta(10)*gw_simul(t-4) + ...
        gcpi_beta.beta(11)*grpe_simul(t) + ...
        gcpi_beta.beta(12)*grpe_simul(t-1) + ...
        gcpi_beta.beta(13)*grpe_simul(t-2) + ...
        gcpi_beta.beta(14)*grpe_simul(t-3) + ...
        gcpi_beta.beta(15)*grpe_simul(t-4) + ...
        gcpi_beta.beta(16)*grpf_simul(t) + ...
        gcpi_beta.beta(17)*grpf_simul(t-1) + ...
        gcpi_beta.beta(18)*grpf_simul(t-2) + ...
        gcpi_beta.beta(19)*grpf_simul(t-3) + ...
        gcpi_beta.beta(20)*grpf_simul(t-4) + ...
        gcpi_beta.beta(21)*shortage_simul(t) + ...
        gcpi_beta.beta(22)*shortage_simul(t-1) + ...
        gcpi_beta.beta(23)*shortage_simul(t-2) + ...
        gcpi_beta.beta(24)*shortage_simul(t-3) + ...
        gcpi_beta.beta(25)*shortage_simul(t-4) + ...
        gcpi_beta.beta(26);

        diffcpicf_simul(t) = 0.25*(gcpi_simul(t) + gcpi_simul(t-1) +...
        gcpi_simul(t-2) + gcpi_simul(t-3)) - cf1_simul(t-4);

        cf10_simul(t) = cf10_beta.beta(1)*cf10_simul(t-1) +...
        cf10_beta.beta(2)*cf10_simul(t-2) +...
        cf10_beta.beta(3)*cf10_simul(t-3) +...
        cf10_beta.beta(4)*cf10_simul(t-4) +...
        cf10_beta.beta(5)*gcpi_simul(t) +...
        cf10_beta.beta(6)*gcpi_simul(t-1) +...
        cf10_beta.beta(7)*gcpi_simul(t-2) +...
        cf10_beta.beta(8)*gcpi_simul(t-3) +...
        cf10_beta.beta(9)*gcpi_simul(t-4);

        cf1_simul(t) = cf1_beta.beta(1)*cf1_simul(t-1)+...
        cf1_beta.beta(2)*cf1_simul(t-2)+...
        cf1_beta.beta(3)*cf1_simul(t-3) +...
        cf1_beta.beta(4)*cf1_simul(t-4)+...
        cf1_beta.beta(5)*cf10_simul(t) +...
        cf1_beta.beta(6)*cf10_simul(t-1)+...
        cf1_beta.beta(7)*cf10_simul(t-2)+...
        cf1_beta.beta(8)*cf10_simul(t-3) +...
        cf1_beta.beta(9)*cf10_simul(t-4)+...
        cf1_beta.beta(10)*gcpi_simul(t) +...
        cf1_beta.beta(11)*gcpi_simul(t-1) +...
        cf1_beta.beta(12)*gcpi_simul(t-2) +...
        cf1_beta.beta(13)*gcpi_simul(t-3) +...
        cf1_beta.beta(14)*gcpi_simul(t-4);

    end

    qtr_lbls = string.empty;
    % crosswalk = containers.Map([1, 2, 3, 4], ["Jan", "Apr", "Jul", "Oct"]);
    for step = 1:timesteps
        lbl = period(step);
        lbl_year = num2str(year(lbl));
        lbl_quarter = num2str(quarter(lbl));
        qtr_lbls(step) = lbl_year + " Q" + lbl_quarter;
    end

    out_data = table(period.', qtr_lbls.', ...
        gw_simul.',...
        gcpi_simul.',...
        cf1_simul.',...
        cf10_simul.',...
        grpe_simul',...
        grpf_simul.',...
        vu_simul.',...
        shortage_simul.', ...
        'VariableNames',["period", "qtr_lbls", "gw_simul",...
        "gcpi_simul",...
        "cf1_simul",...
        "cf10_simul",...
        "grpe_simul",...
        "grpf_simul",...
        "vu_simul",...
        "shortage_simul"]);

end



