clear all
close all 
clc

%% Current analysis: add dummy variables to Q2/Q3 2020 (covid). 
% Need to change:
% 1) the cd() file path,
% 2) the data names for the data and coefficients
% 3) the export data file names.

%% README
% This file generates the output to create figures 12 and 13 from Bernanke and Blanchard (2023).
% Please contact Sam Boocker (Brookings Institution) for questions or
% comments about this code. 

% To run, follow the following steps:
% -- 1) Change your working directory.
% -- 2) Change any specifications for the model that are needed. 
% -- 3) Input the function parameters, ie, shocks you want to remove. 
% -- 4) If you want to export the data, specify the file and location. 

%% Set CD
% Change the file path. 
cd("..\Replication Package\Code and Data\(2) Regressions\Output Data (Full Sample)")

% Output path. 
output_path = "..\Replication Package\Code and Data\(3) Core Results\Decompositions\Output Data";

%% Import and format data
% Inititialize variables showing historical data
data = readtable("eq_simulations_data.xls", VariableNamingRule = 'preserve');
data = data(data.period >= datetime(2018,10,1), :);

%% Specify combinations shocks that we are interested in. 
% The following specifications are employed used to graph figures 12 and 13
% (see Python code for the graphs). To specify your own combinations of
% shocks, simply call the function again below. Function arguments and
% details about the function can be found below. 
remove_all = dynamic_simul(data, true, true, true, true, true, true, true);
remove_grpe = dynamic_simul(data, true, false, false, false, false, false, false);
remove_grpf = dynamic_simul(data, false, true, false, false, false, false, false);
remove_vu = dynamic_simul(data, false, false, true, false, false, false, false);
remove_shortage = dynamic_simul(data, false, false, false, true, false, false, false);
remove_magpty = dynamic_simul(data, false, false, false, false, true, false, false);

remove_dummy2020_q2 = dynamic_simul(data, false, false, false, false, false, true, false);
remove_dummy2020_q3 = dynamic_simul(data, false, false, false, false, false, false, true);

%% Export data. 
cd(output_path)

writetable(remove_all, "remove_all.xls")
writetable(remove_grpe, "remove_grpe.xls")
writetable(remove_grpf, "remove_grpf.xls")
writetable(remove_shortage, "remove_shortage.xls")
writetable(remove_vu, "remove_vu.xls")
writetable(remove_magpty, "remove_magpty.xls")
writetable(remove_dummy2020_q2, "remove_2020q2.xls")
writetable(remove_dummy2020_q3, "remove_2020q3.xls")

%% Function to run simulation with shocks removed.
% The following function takes as input the following variables:
% -- ...
function out_data_2 = dynamic_simul(data, ...
    remove_grpe, remove_grpf, remove_vu, remove_shortage, remove_magpty, ...
    remove_dummy2020_q2, remove_dummy2020_q3)

    % Endogenous variables.
    gw = data.gw.';
    gcpi = data.gcpi.';
    cf1 = data.cf1.';
    cf10 = data.cf10.';
    diffcpicf = data.diffcpicf.';

    % Exogenous variables. 
    grpe = data.grpe.';
    grpf = data.grpf.';
    vu = data.vu.';
    shortage = data.shortage.';
    magpty = data.magpty.';
    
    % Import coefficients
    format long
    gw_beta = readtable("eq_coefficients.xlsx", 'Sheet', "gw");
    gcpi_beta = readtable("eq_coefficients.xlsx", 'Sheet', "gcpi");
    cf1_beta = readtable("eq_coefficients.xlsx", 'Sheet', "cf1");
    cf10_beta = readtable("eq_coefficients.xlsx", 'Sheet', "cf10");

    % Define dummy variables
    % Initialize dummy variables. 
    dummy_q2 = zeros(1,length(gw));
    dummy_q2(7) = 1.0;

    dummy_q3 = zeros(1,length(gw));
    dummy_q3(8) = 1.0;

    timesteps = size(data,1);
    period = data.period.';

    % Initialize variables.

    % Initialize endogenous variables for simulation. 
    % Since we need 4 values before we can run the simulation (because we have
    % 4 lags), we need to initialize the first 4 values of cf1_simul to the
    % actual data. Initialize also diffcpicf (we simulate this as well since 
    % gcpi and cf1 are endogenous).
    gw_simul = gw(1:4);
    gcpi_simul(1:4) = gcpi(1:4);
    cf1_simul(1:4) = cf1(1:4);
    cf10_simul(1:4) = cf10(1:4);
    diffcpicf_simul = diffcpicf(1:4);

    dummy_q2_simul = dummy_q2;
    dummy_q3_simul = dummy_q3;

    % Initialize shock variables for simulation. We set values to zero if shock
    % is removed.
    grpe_simul = grpe;
    grpf_simul = grpf;
    vu_simul = vu;
    shortage_simul = shortage;
    magpty_simul = magpty;

    shocks_removed = {};
    step = 1;
    if remove_grpe == true
        shocks_removed{step} = "grpe";
        step = step + 1;
    end

    if remove_grpf == true
        shocks_removed{step} = "grpf";
        step = step + 1;
    end

    if remove_vu == true
        shocks_removed{step} = "vu";
        step = step + 1;
    end

    if remove_shortage == true
        shocks_removed{step} = "shortage";
        step = step + 1; 
    end

    if remove_magpty == true
        shocks_removed{step} = "magpty";
        step = step + 1;
    end

    if remove_dummy2020_q2 == true
        shocks_removed{step} = "dummy2020_q2";
        step = step + 1; 
    end

    if remove_dummy2020_q3 == true
        shocks_removed{step} = "dummy2020_q3";
        step = step + 1;
    end

    % Run simulation with exogenous shocks removed as specified above. 

    for t = 5:timesteps

        % We now define the exogenous shocks based on the above specification.

        % If energy price shocks (growth rate) are removed, then set the growth
        % rate of energy prices to 0. 
        if remove_grpe == true
            grpe_simul(t) = 0;
        end

        % If food price shocks (growth rate) are removed, then set the growth
        % rate of food prices to 0.
        if remove_grpf == true
            grpf_simul(t) = 0;
        end

        % If Beveridge Curve (v/u; labor market tightness) shocks are removed,
        % then set the labor market tightness parameter equal to its long run
        % constant rate.
        if remove_vu == true
            vu_simul(t) = data.vu(5);
        end

        % If we remove the shortage shock, set equal to long run assumed
        % constant rate. 
        if remove_shortage == true
            shortage_simul(t) = 5;
        end

        % If we remove the productivity shock, set the assumed long run 
        % equal to 2. 
        if remove_magpty == true
            magpty_simul(t) = 2;
        end

        % If we remove the 2020 Q2 dummy, we set equal to 0.0 (ie, do not
        % change). Otherwise, we include the dummy. 
        if remove_dummy2020_q2 == true
            dummy_q2_simul(t) = 0.0;
        end

        if remove_dummy2020_q3 == true
            dummy_q3_simul(t) = 0.0;
        end

        % Simulation of the wage equation at time t. 
        gw_simul(t) = gw_beta.beta(1) * gw_simul(t-1) + ...
            gw_beta.beta(2) * gw_simul(t-2) + ...
            gw_beta.beta(3) * gw_simul(t-3) + ...
            gw_beta.beta(4) * gw_simul(t-4) + ...
            gw_beta.beta(5) * cf1_simul(t-1) + ...
            gw_beta.beta(6) * cf1_simul(t-2) + ...
            gw_beta.beta(7) * cf1_simul(t-3) + ...
            gw_beta.beta(8) * cf1_simul(t-4) + ...
            gw_beta.beta(9) * magpty_simul(t-1) + ...
            gw_beta.beta(10) * vu_simul(t-1) + ...
            gw_beta.beta(11) * vu_simul(t-2) + ...
            gw_beta.beta(12) * vu_simul(t-3) + ...
            gw_beta.beta(13) * vu_simul(t-4) + ...
            gw_beta.beta(14) * diffcpicf_simul(t-1) + ...
            gw_beta.beta(15) * diffcpicf_simul(t-2) + ...
            gw_beta.beta(16) * diffcpicf_simul(t-3) + ...
            gw_beta.beta(17) * diffcpicf_simul(t-4) + ...
            gw_beta.beta(18) * dummy_q2_simul(t) + ...
            gw_beta.beta(19) * dummy_q3_simul(t) + ...
            gw_beta.beta(20);

        % Simulation of the price (inflation) equation at time t. 
        gcpi_simul(t) = gcpi_beta.beta(1) * magpty_simul(t) + ...
            gcpi_beta.beta(2) * gcpi_simul(t-1) + ...
            gcpi_beta.beta(3) * gcpi_simul(t-2) + ...
            gcpi_beta.beta(4) * gcpi_simul(t-3) + ...
            gcpi_beta.beta(5) * gcpi_simul(t-4) + ...
            gcpi_beta.beta(6) * gw_simul(t) + ...
            gcpi_beta.beta(7) * gw_simul(t-1) + ...
            gcpi_beta.beta(8) * gw_simul(t-2) + ...
            gcpi_beta.beta(9) * gw_simul(t-3) + ...
            gcpi_beta.beta(10) * gw_simul(t-4) + ...
            gcpi_beta.beta(11) * grpe_simul(t) + ...
            gcpi_beta.beta(12) * grpe_simul(t-1) + ...
            gcpi_beta.beta(13) * grpe_simul(t-2) + ...
            gcpi_beta.beta(14) * grpe_simul(t-3) + ...
            gcpi_beta.beta(15) * grpe_simul(t-4) + ...
            gcpi_beta.beta(16) * grpf_simul(t) + ...
            gcpi_beta.beta(17) * grpf_simul(t-1) + ...
            gcpi_beta.beta(18) * grpf_simul(t-2) + ...
            gcpi_beta.beta(19) * grpf_simul(t-3) + ...
            gcpi_beta.beta(20) * grpf_simul(t-4) + ...
            gcpi_beta.beta(21) * shortage_simul(t) + ...
            gcpi_beta.beta(22) * shortage_simul(t-1) + ...
            gcpi_beta.beta(23) * shortage_simul(t-2) + ...
            gcpi_beta.beta(24) * shortage_simul(t-3) + ...
            gcpi_beta.beta(25) * shortage_simul(t-4) + ...
            gcpi_beta.beta(26);

        % Simulation of the catch-up term (as specified in data construction).
        diffcpicf_simul(t) = 0.25*(gcpi_simul(t) + gcpi_simul(t-1) +... 
            gcpi_simul(t-2) + gcpi_simul(t-3)) - cf1_simul(t-4);

        % Simulation of long run inflation expectations equation.
        cf10_simul(t) = cf10_beta.beta(1) * cf10_simul(t-1) + ...
            cf10_beta.beta(2) * cf10_simul(t-2) + ...
            cf10_beta.beta(3) * cf10_simul(t-3) + ...
            cf10_beta.beta(4) * cf10_simul(t-4) + ...
            cf10_beta.beta(5) * gcpi_simul(t) + ...
            cf10_beta.beta(6) * gcpi_simul(t-1) + ...
            cf10_beta.beta(7) * gcpi_simul(t-2) + ...
            cf10_beta.beta(8) * gcpi_simul(t-3) + ...
            cf10_beta.beta(9) * gcpi_simul(t-4);
        
        % Simulation of short run inflation expectations equation. 
            cf1_simul(t) = cf1_beta.beta(1) * cf1_simul(t-1) + ...
            cf1_beta.beta(2) * cf1_simul(t-2) + ...
            cf1_beta.beta(3) * cf1_simul(t-3) + ...
            cf1_beta.beta(4) * cf1_simul(t-4) + ...
            cf1_beta.beta(5) * cf10_simul(t) + ...
            cf1_beta.beta(6) * cf10_simul(t-1) + ...
            cf1_beta.beta(7) * cf10_simul(t-2) + ...
            cf1_beta.beta(8) * cf10_simul(t-3) + ...
            cf1_beta.beta(9) * cf10_simul(t-4) + ...
            cf1_beta.beta(10) * gcpi_simul(t) + ...
            cf1_beta.beta(11) * gcpi_simul(t-1) + ...
            cf1_beta.beta(12) * gcpi_simul(t-2) + ...
            cf1_beta.beta(13) * gcpi_simul(t-3) + ...
            cf1_beta.beta(14) * gcpi_simul(t-4);
    end

    % Run the simulation with all exogenous shocks included; this is the 
    % baseline specification. 

    gw_simul_baseline = gw(1:4);
    gcpi_simul_baseline = gcpi(1:4);
    cf1_simul_baseline = cf1(1:4);
    cf10_simul_baseline = cf10(1:4);
    diffcpicf_simul_baseline = diffcpicf(1:4);

    for t = 5:timesteps

        % Equation not adding residuals in
        gw_simul_baseline(t) = gw_beta.beta(1)*gw_simul_baseline(t-1)+...
            gw_beta.beta(2) * gw_simul_baseline(t-2)+...
            gw_beta.beta(3) * gw_simul_baseline(t-3) +...
            gw_beta.beta(4) * gw_simul_baseline(t-4)+...
            gw_beta.beta(5) * cf1_simul_baseline(t-1) +...
            gw_beta.beta(6) * cf1_simul_baseline(t-2) +...
            gw_beta.beta(7) * cf1_simul_baseline(t-3) +...
            gw_beta.beta(8) * cf1_simul_baseline(t-4)+...
            gw_beta.beta(9) * magpty(t-1) + ...
            gw_beta.beta(10) * vu(t-1) + ...
            gw_beta.beta(11) * vu(t-2)+...
            gw_beta.beta(12) * vu(t-3) + gw_beta.beta(13)*vu(t-4) +...
            gw_beta.beta(14) * diffcpicf_simul_baseline(t-1) +...
            gw_beta.beta(15) * diffcpicf_simul_baseline(t-2)+...
            gw_beta.beta(16) * diffcpicf_simul_baseline(t-3)+...
            gw_beta.beta(17) * diffcpicf_simul_baseline(t-4) +...
            gw_beta.beta(18) * dummy_q2(t) + ...
            gw_beta.beta(19) * dummy_q3(t) + ...
            gw_beta.beta(20);

        gcpi_simul_baseline(t) =  gcpi_beta.beta(1)*magpty(t) +...
            gcpi_beta.beta(2)*gcpi_simul_baseline(t-1) +...
            gcpi_beta.beta(3)*gcpi_simul_baseline(t-2) +...
            gcpi_beta.beta(4)*gcpi_simul_baseline(t-3) +...
            gcpi_beta.beta(5)*gcpi_simul_baseline(t-4) + ...
            gcpi_beta.beta(6)*gw_simul_baseline(t) +...
            gcpi_beta.beta(7)*gw_simul_baseline(t-1)+...
            gcpi_beta.beta(8)*gw_simul_baseline(t-2) +...
            gcpi_beta.beta(9)*gw_simul_baseline(t-3) +...
            gcpi_beta.beta(10)*gw_simul_baseline(t-4) +...
            gcpi_beta.beta(11)*grpe(t) +...
            gcpi_beta.beta(12)*grpe(t-1) +...
            gcpi_beta.beta(13)*grpe(t-2) + gcpi_beta.beta(14)*grpe(t-3) +...
            gcpi_beta.beta(15)*grpe(t-4) +...
            gcpi_beta.beta(16)*grpf(t) +...
            gcpi_beta.beta(17)*grpf(t-1) +...
            gcpi_beta.beta(18)*grpf(t-2) +...
            gcpi_beta.beta(19)*grpf(t-3) +...
            gcpi_beta.beta(20)*grpf(t-4) +...
            gcpi_beta.beta(21)*shortage(t) +...
            gcpi_beta.beta(22)*shortage(t-1) +...
            gcpi_beta.beta(23)*shortage(t-2) +...
            gcpi_beta.beta(24)*shortage(t-3) +...
            gcpi_beta.beta(25)*shortage(t-4) +...
            gcpi_beta.beta(26);

        diffcpicf_simul_baseline(t) = 0.25*(gcpi_simul_baseline(t) +...
                gcpi_simul_baseline(t-1) +...
            gcpi_simul_baseline(t-2) + gcpi_simul_baseline(t-3)) -...
            cf1_simul_baseline(t-4);
        
        cf10_simul_baseline(t) = cf10_beta.beta(1)*cf10_simul_baseline(t-1) +...
            cf10_beta.beta(2)*cf10_simul_baseline(t-2) +...
            cf10_beta.beta(3)*cf10_simul_baseline(t-3) +...
            cf10_beta.beta(4)*cf10_simul_baseline(t-4) +...
            cf10_beta.beta(5)*gcpi_simul_baseline(t) +...
            cf10_beta.beta(6)*gcpi_simul_baseline(t-1) +...
            cf10_beta.beta(7)*gcpi_simul_baseline(t-2) +...
            cf10_beta.beta(8)*gcpi_simul_baseline(t-3) +...
            cf10_beta.beta(9)*gcpi_simul_baseline(t-4);
        
        cf1_simul_baseline(t) = cf1_beta.beta(1)*cf1_simul_baseline(t-1)+...
            cf1_beta.beta(2)*cf1_simul_baseline(t-2)+...
            cf1_beta.beta(3)*cf1_simul_baseline(t-3) +...
            cf1_beta.beta(4)*cf1_simul_baseline(t-4)+...
            cf1_beta.beta(5)*cf10_simul_baseline(t) +...
            cf1_beta.beta(6)*cf10_simul_baseline(t-1)+...
            cf1_beta.beta(7)*cf10_simul_baseline(t-2)+...
            cf1_beta.beta(8)*cf10_simul_baseline(t-3) +...
            cf1_beta.beta(9)*cf10_simul_baseline(t-4)+...
            cf1_beta.beta(10)*gcpi_simul_baseline(t) +...
            cf1_beta.beta(11)*gcpi_simul_baseline(t-1) +...
            cf1_beta.beta(12)*gcpi_simul_baseline(t-2) +...
            cf1_beta.beta(13)*gcpi_simul_baseline(t-3) +...
            cf1_beta.beta(14)*gcpi_simul_baseline(t-4);

    end


    out_data = table(period.', gw.', gw_simul.', gw_simul_baseline.',...
        gcpi.', gcpi_simul.', gcpi_simul_baseline.',...
        cf1.', cf1_simul.', cf1_simul_baseline.',...
        cf10.', cf10_simul.', cf10_simul_baseline.',...
        grpe.', grpe_simul',...
        grpf.', grpf_simul.',...
        vu.', vu_simul.',...
        shortage.', shortage_simul.', ...
        magpty.', magpty_simul.', ...
        'VariableNames',["period", "gw", "gw_simul", "gw_simul_baseline",...
        "gcpi", "gcpi_simul", "gcpi_simul_baseline",...
        "cf1", "cf1_simul", "cf1_simul_baseline",...
        "cf10", "cf10_simul", "cf10_simul_baseline",...
        "grpe", "grpe_simul",...
        "grpf", "grpf_simul",...
        "vu", "vu_simul",...
        "shortage", "shortage_simul", ...
        "magpty", "magpty_simul"]);

        % Calculated contributions of shocks.
        if size(shocks_removed, 2) == 1
            contr_gw = gw_simul_baseline - gw_simul;
            contr_gcpi = gcpi_simul_baseline - gcpi_simul;
            contr_cf1 = cf1_simul_baseline - cf1_simul;
            contr_cf10 = cf10_simul_baseline - cf10_simul;

            out_data_2 = table(contr_gw.', contr_gcpi.', contr_cf1.',...
                contr_cf10.', 'VariableNames',[shocks_removed{1} + "_contr_gw",...
                shocks_removed{1} + "_contr_gcpi", shocks_removed{1} +...
                "_contr_cf1", shocks_removed{1} + "_contr_cf10"]);
                out_data = [out_data out_data_2];
        else size(shocks_removed, 2) == 4;
            out_data_2 = out_data;
        end
        
end


